version: "3"
services:
  authentication-client:
    build: ./Authentication/client
    ports:
      - 5173:5173
    depends_on:
      - mongo
      - authentication-server
    environment:
      - VITE_AUTENTICATION_SERVER_URL=
      - VITE_MAIN_APPLICATION_CLIENT_URL=

  authentication-server:
    build: ./Authentication/server
    ports:
      - 3001:3001
    depends_on:
      - mongo
    environment:
      - SECRET_KEY=
      - MONGO_CONNECTION_STRING=
      - MONGO_EMPLOYEE_DB=

  main-application-client:
    build: ./mainApplication/Timesheet_frontSdk
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SECRET_KEY=
      - VITE_AUTHENTICATION_SERVER_URL=
      - VITE_POLICY_SERVER_URL=
      - VITE_AUTHENTICATION_CLIENT_URL=

  main-application-server:
    build: ./mainApplication/Timesheet_server
    ports:
      - "8090:8090"
    depends_on:
      - mongo
    environment:
    - SECRET_KEY=
    - VITE_AUTHENTICATION_SERVER_URL=
    - VITE_POLICY_SERVER_URL=
    - DB_URL=

  policy-server:
    build: ./policyServerJs
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_CONNECTION_STRING=
      - MONGO_POLICY_CONFIGURATION_DB=
      - ALLOWED_ORIGINS=[]

  policy-configuration-client:
    build: ./policyConfiguration/client
    ports:
      - 5174:5174
    depends_on:
      - mongo
      - policy-configuration-server
    environment:
      - VITE_SERVER_PORT=
      - VITE_BASE_URL=
      - VITE_POLICY_CONFIGURATION_SERVER_URL=
      - VITE_GITHUB_CLIENT_ID=

  policy-configuration-server:
    build: ./policyConfiguration/server
    ports:
      - 3002:3002
    depends_on:
      - mongo
    environment:
      - SERVER_PORT=
      - GITHUB_CLIENT_ID=
      - GITHUB_CLIENT_SECRET=
      - MONGO_CONNECTION_STRING=
      - MONGO_POLICY_CONFIGURATION_DB=
      - GITHUB_AUTH_URL=
      - GITHUB_USER_URL=

  mongo:
    image: mongo
    ports:
      - 27017:27017
    expose:
      - '27017'
    volumes:
      - ./mongo-setup:/docker-entrypoint-initdb.d
